// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 插件注册信息
type PluginInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RoutePrefix    string                 `protobuf:"bytes,4,opt,name=route_prefix,json=routePrefix,proto3" json:"route_prefix,omitempty"`
	Menus          []*MenuItem            `protobuf:"bytes,5,rep,name=menus,proto3" json:"menus,omitempty"`
	Perms          []*Permission          `protobuf:"bytes,6,rep,name=perms,proto3" json:"perms,omitempty"`
	FrontendBundle string                 `protobuf:"bytes,7,opt,name=frontend_bundle,json=frontendBundle,proto3" json:"frontend_bundle,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetRoutePrefix() string {
	if x != nil {
		return x.RoutePrefix
	}
	return ""
}

func (x *PluginInfo) GetMenus() []*MenuItem {
	if x != nil {
		return x.Menus
	}
	return nil
}

func (x *PluginInfo) GetPerms() []*Permission {
	if x != nil {
		return x.Perms
	}
	return nil
}

func (x *PluginInfo) GetFrontendBundle() string {
	if x != nil {
		return x.FrontendBundle
	}
	return ""
}

type MenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Icon          string                 `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Sort          int32                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Children      []*MenuItem            `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *MenuItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MenuItem) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *MenuItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MenuItem) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *MenuItem) GetChildren() []*MenuItem {
	if x != nil {
		return x.Children
	}
	return nil
}

type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Permission) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Permission) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type HttpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Query         string                 `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	UserId        int64                  `protobuf:"varint,10,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      int64                  `protobuf:"varint,11,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Roles         []string               `protobuf:"bytes,12,rep,name=roles,proto3" json:"roles,omitempty"`
	Permissions   []string               `protobuf:"bytes,13,rep,name=permissions,proto3" json:"permissions,omitempty"`
	DbDsn         string                 `protobuf:"bytes,14,opt,name=db_dsn,json=dbDsn,proto3" json:"db_dsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HttpRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *HttpRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HttpRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *HttpRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *HttpRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *HttpRequest) GetDbDsn() string {
	if x != nil {
		return x.DbDsn
	}
	return ""
}

type HttpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *HttpResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HttpResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type CallPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetPlugin  string                 `protobuf:"bytes,1,opt,name=target_plugin,json=targetPlugin,proto3" json:"target_plugin,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	ActionVersion string                 `protobuf:"bytes,4,opt,name=action_version,json=actionVersion,proto3" json:"action_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallPluginRequest) Reset() {
	*x = CallPluginRequest{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallPluginRequest) ProtoMessage() {}

func (x *CallPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallPluginRequest.ProtoReflect.Descriptor instead.
func (*CallPluginRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *CallPluginRequest) GetTargetPlugin() string {
	if x != nil {
		return x.TargetPlugin
	}
	return ""
}

func (x *CallPluginRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallPluginRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CallPluginRequest) GetActionVersion() string {
	if x != nil {
		return x.ActionVersion
	}
	return ""
}

type CallPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallPluginResponse) Reset() {
	*x = CallPluginResponse{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallPluginResponse) ProtoMessage() {}

func (x *CallPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallPluginResponse.ProtoReflect.Descriptor instead.
func (*CallPluginResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *CallPluginResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CallPluginResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x11gameserver_plugin\"\x90\x02\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\froute_prefix\x18\x04 \x01(\tR\vroutePrefix\x121\n" +
	"\x05menus\x18\x05 \x03(\v2\x1b.gameserver_plugin.MenuItemR\x05menus\x123\n" +
	"\x05perms\x18\x06 \x03(\v2\x1d.gameserver_plugin.PermissionR\x05perms\x12'\n" +
	"\x0ffrontend_bundle\x18\a \x01(\tR\x0efrontendBundle\"\x95\x01\n" +
	"\bMenuItem\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04icon\x18\x02 \x01(\tR\x04icon\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x05R\x04sort\x127\n" +
	"\bchildren\x18\x05 \x03(\v2\x1b.gameserver_plugin.MenuItemR\bchildren\"4\n" +
	"\n" +
	"Permission\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"\xeb\x02\n" +
	"\vHttpRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12E\n" +
	"\aheaders\x18\x03 \x03(\v2+.gameserver_plugin.HttpRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12\x14\n" +
	"\x05query\x18\x05 \x01(\tR\x05query\x12\x17\n" +
	"\auser_id\x18\n" +
	" \x01(\x03R\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\v \x01(\x03R\btenantId\x12\x14\n" +
	"\x05roles\x18\f \x03(\tR\x05roles\x12 \n" +
	"\vpermissions\x18\r \x03(\tR\vpermissions\x12\x15\n" +
	"\x06db_dsn\x18\x0e \x01(\tR\x05dbDsn\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc7\x01\n" +
	"\fHttpResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12F\n" +
	"\aheaders\x18\x02 \x03(\v2,.gameserver_plugin.HttpResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x11CallPluginRequest\x12#\n" +
	"\rtarget_plugin\x18\x01 \x01(\tR\ftargetPlugin\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"D\n" +
	"\x12CallPluginResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"k\n" +
	"\x05Event\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\a\n" +
	"\x05Empty\"D\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x8c\x03\n" +
	"\rPluginService\x12C\n" +
	"\bRegister\x12\x18.gameserver_plugin.Empty\x1a\x1d.gameserver_plugin.PluginInfo\x12P\n" +
	"\rHandleRequest\x12\x1e.gameserver_plugin.HttpRequest\x1a\x1f.gameserver_plugin.HttpResponse\x12J\n" +
	"\vHealthcheck\x12\x18.gameserver_plugin.Empty\x1a!.gameserver_plugin.HealthResponse\x12=\n" +
	"\aOnEvent\x12\x18.gameserver_plugin.Event\x1a\x18.gameserver_plugin.Empty\x12Y\n" +
	"\n" +
	"CallPlugin\x12$.gameserver_plugin.CallPluginRequest\x1a%.gameserver_plugin.CallPluginResponse2\xac\x01\n" +
	"\vHostService\x12B\n" +
	"\fPublishEvent\x12\x18.gameserver_plugin.Event\x1a\x18.gameserver_plugin.Empty\x12Y\n" +
	"\n" +
	"CallPlugin\x12$.gameserver_plugin.CallPluginRequest\x1a%.gameserver_plugin.CallPluginResponseB!Z\x1fplatform-admin/plugin-sdk/protob\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_plugin_proto_goTypes = []any{
	(*PluginInfo)(nil),         // 0: gameserver_plugin.PluginInfo
	(*MenuItem)(nil),           // 1: gameserver_plugin.MenuItem
	(*Permission)(nil),         // 2: gameserver_plugin.Permission
	(*HttpRequest)(nil),        // 3: gameserver_plugin.HttpRequest
	(*HttpResponse)(nil),       // 4: gameserver_plugin.HttpResponse
	(*CallPluginRequest)(nil),  // 5: gameserver_plugin.CallPluginRequest
	(*CallPluginResponse)(nil), // 6: gameserver_plugin.CallPluginResponse
	(*Event)(nil),              // 7: gameserver_plugin.Event
	(*Empty)(nil),              // 8: gameserver_plugin.Empty
	(*HealthResponse)(nil),     // 9: gameserver_plugin.HealthResponse
	nil,                        // 10: gameserver_plugin.HttpRequest.HeadersEntry
	nil,                        // 11: gameserver_plugin.HttpResponse.HeadersEntry
}
var file_plugin_proto_depIdxs = []int32{
	1,  // 0: gameserver_plugin.PluginInfo.menus:type_name -> gameserver_plugin.MenuItem
	2,  // 1: gameserver_plugin.PluginInfo.perms:type_name -> gameserver_plugin.Permission
	1,  // 2: gameserver_plugin.MenuItem.children:type_name -> gameserver_plugin.MenuItem
	10, // 3: gameserver_plugin.HttpRequest.headers:type_name -> gameserver_plugin.HttpRequest.HeadersEntry
	11, // 4: gameserver_plugin.HttpResponse.headers:type_name -> gameserver_plugin.HttpResponse.HeadersEntry
	8,  // 5: gameserver_plugin.PluginService.Register:input_type -> gameserver_plugin.Empty
	3,  // 6: gameserver_plugin.PluginService.HandleRequest:input_type -> gameserver_plugin.HttpRequest
	8,  // 7: gameserver_plugin.PluginService.Healthcheck:input_type -> gameserver_plugin.Empty
	7,  // 8: gameserver_plugin.PluginService.OnEvent:input_type -> gameserver_plugin.Event
	5,  // 9: gameserver_plugin.PluginService.CallPlugin:input_type -> gameserver_plugin.CallPluginRequest
	7,  // 10: gameserver_plugin.HostService.PublishEvent:input_type -> gameserver_plugin.Event
	5,  // 11: gameserver_plugin.HostService.CallPlugin:input_type -> gameserver_plugin.CallPluginRequest
	0,  // 12: gameserver_plugin.PluginService.Register:output_type -> gameserver_plugin.PluginInfo
	4,  // 13: gameserver_plugin.PluginService.HandleRequest:output_type -> gameserver_plugin.HttpResponse
	9,  // 14: gameserver_plugin.PluginService.Healthcheck:output_type -> gameserver_plugin.HealthResponse
	8,  // 15: gameserver_plugin.PluginService.OnEvent:output_type -> gameserver_plugin.Empty
	6,  // 16: gameserver_plugin.PluginService.CallPlugin:output_type -> gameserver_plugin.CallPluginResponse
	8,  // 17: gameserver_plugin.HostService.PublishEvent:output_type -> gameserver_plugin.Empty
	6,  // 18: gameserver_plugin.HostService.CallPlugin:output_type -> gameserver_plugin.CallPluginResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
